# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rcqrs}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ben Smith"]
  s.date = %q{2010-09-22}
  s.description = %q{A Ruby implementation of Command-Query Responsibility Segregation (CQRS) with Event Sourcing, based upon the ideas of Greg Young.}
  s.email = %q{ben@slashdotdash.net}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".gitignore",
     "Gemfile",
     "Gemfile.lock",
     "README.md",
     "lib/boot.rb",
     "lib/bus/command_bus.rb",
     "lib/bus/event_bus.rb",
     "lib/bus/router.rb",
     "lib/commands/active_model.rb",
     "lib/commands/invalid_command.rb",
     "lib/commands/handlers/base_handler.rb",
     "lib/domain/aggregate_root.rb",
     "lib/event_store/adapters/active_record_adapter.rb",
     "lib/event_store/adapters/in_memory_adapter.rb",
     "lib/event_store/domain_event_storage.rb",
     "lib/event_store/domain_repository.rb",
     "lib/events/domain_event.rb",
     "lib/events/handlers/base_handler.rb",
     "lib/rcqrs.rb",
     "lib/support/guid.rb",
     "lib/support/initializer.rb",
     "lib/support/serialization.rb",
     "spec/bus/command_bus_spec.rb",
     "spec/bus/command_router_spec.rb",
     "spec/bus/event_bus_spec.rb",
     "spec/commands/create_company_command.rb",
     "spec/commands/handlers/command_handler_spec.rb",
     "spec/commands/handlers/create_company_handler.rb",
     "spec/domain/company.rb",
     "spec/domain/company_spec.rb",
     "spec/domain/expense.rb",
     "spec/domain/invoice.rb",
     "spec/event_store/active_record_adapter_spec.rb",
     "spec/event_store/domain_repository_spec.rb",
     "spec/events/company_created_event.rb",
     "spec/events/domain_event_spec.rb",
     "spec/events/handlers/company_created_handler.rb",
     "spec/events/handlers/event_handler_spec.rb",
     "spec/events/invoice_created_event.rb",
     "spec/initializer_spec.rb",
     "spec/mock_router.rb",
     "spec/reporting/company.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/slashdotdash/rcqrs}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{CQRS library in Ruby}
  s.test_files = [
    "spec/bus/command_bus_spec.rb",
     "spec/bus/command_router_spec.rb",
     "spec/bus/event_bus_spec.rb",
     "spec/commands/create_company_command.rb",
     "spec/commands/handlers/command_handler_spec.rb",
     "spec/commands/handlers/create_company_handler.rb",
     "spec/domain/company.rb",
     "spec/domain/company_spec.rb",
     "spec/domain/expense.rb",
     "spec/domain/invoice.rb",
     "spec/event_store/active_record_adapter_spec.rb",
     "spec/event_store/domain_repository_spec.rb",
     "spec/events/company_created_event.rb",
     "spec/events/domain_event_spec.rb",
     "spec/events/handlers/company_created_handler.rb",
     "spec/events/handlers/event_handler_spec.rb",
     "spec/events/invoice_created_event.rb",
     "spec/initializer_spec.rb",
     "spec/mock_router.rb",
     "spec/reporting/company.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

